// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVmbGj2grSYM7_GNy3QHNG_oybcYGn8MA',
    appId: '1:701660032496:web:fd0c2c8854c12471ec8135',
    messagingSenderId: '701660032496',
    projectId: 'arthiktrack-5fbc7',
    authDomain: 'arthiktrack-5fbc7.firebaseapp.com',
    storageBucket: 'arthiktrack-5fbc7.firebasestorage.app',
    measurementId: 'G-77TZV34X0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuDNtmx8Fu3jTA0UJF24n1caLmZkGGw7Y',
    appId: '1:701660032496:android:709f429cff601618ec8135',
    messagingSenderId: '701660032496',
    projectId: 'arthiktrack-5fbc7',
    storageBucket: 'arthiktrack-5fbc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDEbM8P2EbVxCOJ7c3lbpgl2oGK0Eqtb4',
    appId: '1:701660032496:ios:e2b5d0901a4ae994ec8135',
    messagingSenderId: '701660032496',
    projectId: 'arthiktrack-5fbc7',
    storageBucket: 'arthiktrack-5fbc7.firebasestorage.app',
    iosBundleId: 'com.example.arthiktrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDEbM8P2EbVxCOJ7c3lbpgl2oGK0Eqtb4',
    appId: '1:701660032496:ios:e2b5d0901a4ae994ec8135',
    messagingSenderId: '701660032496',
    projectId: 'arthiktrack-5fbc7',
    storageBucket: 'arthiktrack-5fbc7.firebasestorage.app',
    iosBundleId: 'com.example.arthiktrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVmbGj2grSYM7_GNy3QHNG_oybcYGn8MA',
    appId: '1:701660032496:web:832baa3b072303a6ec8135',
    messagingSenderId: '701660032496',
    projectId: 'arthiktrack-5fbc7',
    authDomain: 'arthiktrack-5fbc7.firebaseapp.com',
    storageBucket: 'arthiktrack-5fbc7.firebasestorage.app',
    measurementId: 'G-QD272NNLDX',
  );
}
